### ISSUE TITLE
Request: Push branches with `av stack sync` before creating a PR

### ISSUE THREAD

**Issue by abatilo** [aviator-co/av#210]
I'm using `av` version `v0.0.25` and was wondering if there's any way to push branches to my remote without actually opening a PR?

I have cases where I might want to push branches in the entire stack to GH while I do other git operations, and I want the branches to be on the remote just in case I mess up some operation where `reflog` would be more work than I want to take on.

At the moment, it seems like I need to manually `av stack next && git push` for each stack branch, but I'm hoping that I'm missing something obvious.

Once I've done a `av stack submit`, it does look like `av` does what I want, but now I might have a bunch of PRs open when really, I wanted to just save a back up of my progress before getting actual eyes on the work.

**Comment by travigd** [comment]
Thanks for reporting this @abatilo! I ended up implementing `av stack for-each` which should be useful for this (I'm not sure it makes sense to disable PR creating for `av stack submit` since that's the main point).

You can do what you want here by running `av stack for-each -- git push` (or the shorter `av st fe -- git push`).

Does that work for you?

**Comment by abatilo** [comment]
@travigd That would do it! Looking forward to that release :D
